import { db } from "./db";
import { bookmakers, bonuses, blogPosts } from "@shared/schema";

export async function seedDatabase() {
  const existingBookmakers = await db.select().from(bookmakers);
  if (existingBookmakers.length > 0) return;

  const bookmakerData = [
    {
      name: "MyStake",
      slug: "mystake",
      logo: "/logos/mystake.png",
      description: "Top-rated crypto sportsbook with 120% welcome bonus, instant crypto payouts, 40+ sports markets, and a legendary VIP program.",
      longDescription: "MyStake has quickly risen to become one of the most popular crypto betting platforms in the world. Founded in 2020, the platform offers a massive selection of over 40 sports and esports markets with competitive odds. Their welcome bonus of 120% up to $600 with just 10x wagering requirement is one of the best in the industry. MyStake supports over 50 cryptocurrencies with zero fees on deposits and withdrawals. Their VIP program features multiple tiers from Bronze to Platinum, offering up to 20% weekly cashback. The platform also features a comprehensive casino with thousands of games, original mini-games, and live dealer options. With a 4.3/5 Trustpilot rating from over 20,000 reviews, MyStake has proven its reliability.",
      websiteUrl: "https://mystake.com",
      affiliateUrl: "https://mystake.com/?ref=betwithoutkyc",
      overallRating: 9.6,
      trustScore: 9.8,
      trustScoreLabel: "Excellent",
      oddsRating: 9.5,
      bonusRating: 9.4,
      uiRating: 9.6,
      supportRating: 9.3,
      payoutSpeed: "Instant",
      minDeposit: "$1",
      maxPayout: "Unlimited",
      established: "2020",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "LTC", "DOGE", "XRP", "TRX", "USDT", "USDC", "BNB", "SOL"],
      sportsCovered: ["Football", "Basketball", "Tennis", "MMA", "Esports", "Cricket", "Baseball", "Boxing", "Rugby", "Golf"],
      pros: ["120% welcome bonus with low 10x wagering", "50+ cryptos with zero fees", "Instant payouts", "40+ sports markets", "VIP program up to 20% cashback", "4.3/5 Trustpilot rating"],
      cons: ["KYC required for large withdrawals", "Not available in some countries", "Casino-heavy marketing"],
      featured: true,
      rank: 1,
      isActive: true,
    },
    {
      name: "Playbet",
      slug: "playbet",
      logo: "/logos/playbet.png",
      description: "Fast-growing crypto sportsbook with 200% welcome bonus up to 1,000 USDT, 4,500+ games, and rapid crypto withdrawals.",
      longDescription: "Playbet is one of the fastest-growing crypto betting platforms, offering an impressive 200% welcome bonus up to 1,000 USDT plus 200 free spins. The platform features over 4,500 games including a comprehensive sportsbook covering traditional sports and esports. Playbet accepts multiple cryptocurrencies and fiat payments, making it accessible to a wide audience. Their mobile-optimized platform ensures a smooth betting experience on any device. With competitive odds across major sports leagues and a clean, modern interface, Playbet is quickly becoming a go-to destination for crypto bettors who want generous bonuses and fast payouts.",
      websiteUrl: "https://playbet.io",
      affiliateUrl: "https://playbet.io/?ref=betwithoutkyc",
      overallRating: 9.3,
      trustScore: 9.5,
      trustScoreLabel: "Excellent",
      oddsRating: 9.1,
      bonusRating: 9.6,
      uiRating: 9.2,
      supportRating: 8.9,
      payoutSpeed: "Instant",
      minDeposit: "$1",
      maxPayout: "$1,000,000",
      established: "2022",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "USDT", "LTC", "DOGE", "XRP", "TRX", "BNB"],
      sportsCovered: ["Football", "Basketball", "Tennis", "Esports", "MMA", "Boxing", "Cricket", "Baseball"],
      pros: ["200% welcome bonus up to 1,000 USDT", "4,500+ games", "Fast crypto withdrawals", "Mobile optimized", "Multi-language support", "200 free spins for new users"],
      cons: ["Relatively new platform", "No no-deposit bonus", "Wagering requirements on bonuses"],
      featured: true,
      rank: 2,
      isActive: true,
    },
    {
      name: "BC.Game",
      slug: "bc-game",
      logo: "/logos/bcgame.png",
      description: "Community-driven crypto casino with 90+ cryptos supported and generous bonuses.",
      longDescription: "BC.Game is a community-first crypto casino and sportsbook that has rapidly grown to become one of the top platforms in the space. Supporting over 90 cryptocurrencies, BC.Game offers unmatched flexibility for crypto users. Their platform features a unique rewards system including daily spins, tasks, and a generous rakeback program. The sportsbook covers major leagues and offers competitive odds, while the casino section includes thousands of slots and table games from top providers.",
      websiteUrl: "https://bc.game",
      affiliateUrl: "https://bc.game/?ref=betwithoutkyc",
      overallRating: 9.2,
      trustScore: 9.5,
      trustScoreLabel: "Excellent",
      oddsRating: 8.9,
      bonusRating: 9.5,
      uiRating: 9.0,
      supportRating: 8.8,
      payoutSpeed: "Instant",
      minDeposit: "$0.01",
      maxPayout: "$2,000,000",
      established: "2017",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "LTC", "DOGE", "XRP", "TRX", "USDT", "SOL", "AVAX", "MATIC"],
      sportsCovered: ["Football", "Basketball", "Tennis", "Esports", "MMA", "Boxing"],
      pros: ["90+ cryptos supported", "Great bonus system", "Active community", "Low minimum deposit", "Daily free spins"],
      cons: ["Interface can be cluttered", "Sportsbook still growing", "KYC may be required"],
      featured: true,
      rank: 3,
      isActive: true,
    },
    {
      name: "Velobet",
      slug: "velobet",
      logo: "/logos/velobet.svg",
      description: "Premium crypto sportsbook offering 150% sports bonus up to $1,000, 10% monthly crypto cashback, and 9 supported languages.",
      longDescription: "Velobet is a premium crypto sportsbook launched in 2023 that has rapidly gained traction among crypto bettors. Their sports welcome bonus of 150% up to $1,000 with a reasonable 15x wagering requirement makes it one of the most attractive offers available. What sets Velobet apart is their 10% monthly crypto cashback with zero wagering requirements - a standout feature in the industry. The platform offers a 160% crypto-specific casino bonus, extensive sports coverage, and supports multiple cryptocurrencies including BTC, ETH, and BCH. Available in 9 languages with a dedicated mobile app, Velobet provides a polished betting experience for the global crypto community.",
      websiteUrl: "https://velobet.com",
      affiliateUrl: "https://velobet.com/?ref=betwithoutkyc",
      overallRating: 9.1,
      trustScore: 9.3,
      trustScoreLabel: "Excellent",
      oddsRating: 9.0,
      bonusRating: 9.3,
      uiRating: 9.1,
      supportRating: 8.8,
      payoutSpeed: "Under 10 minutes",
      minDeposit: "$10",
      maxPayout: "$500,000",
      established: "2023",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "BCH", "USDT", "LTC", "DOGE", "XRP"],
      sportsCovered: ["Football", "Basketball", "Tennis", "MMA", "Esports", "Cricket", "Baseball", "Boxing", "Rugby"],
      pros: ["150% sports welcome bonus", "10% monthly crypto cashback (no wagering)", "160% crypto casino bonus", "9 languages supported", "Mobile app available", "Low minimum deposit"],
      cons: ["Newer platform (2023)", "KYC may be required for withdrawals", "Limited crypto selection vs competitors"],
      featured: true,
      rank: 4,
      isActive: true,
    },
    {
      name: "Stake",
      slug: "stake",
      logo: "/logos/stake.png",
      description: "The world's leading crypto casino and sportsbook with instant payouts and thousands of games.",
      longDescription: "Stake has established itself as the undisputed leader in the crypto gambling space. Founded in 2017, Stake offers an unmatched combination of sports betting, casino games, and original games. Their platform supports instant deposits and withdrawals in multiple cryptocurrencies, with no KYC required for crypto users. The site features a sleek, modern interface and offers some of the best odds in the industry. Their VIP program is legendary, offering personalized rewards and dedicated support for high-volume players.",
      websiteUrl: "https://stake.com",
      affiliateUrl: "https://stake.com/?ref=betwithoutkyc",
      overallRating: 9.5,
      trustScore: 9.8,
      trustScoreLabel: "Excellent",
      oddsRating: 9.4,
      bonusRating: 8.8,
      uiRating: 9.7,
      supportRating: 9.3,
      payoutSpeed: "Instant",
      minDeposit: "$1",
      maxPayout: "Unlimited",
      established: "2017",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "LTC", "DOGE", "XRP", "TRX", "EOS", "BNB"],
      sportsCovered: ["Football", "Basketball", "Tennis", "MMA", "Esports", "Cricket", "Baseball"],
      pros: ["Instant crypto payouts", "No KYC for crypto", "Best VIP program", "Thousands of games", "Provably fair"],
      cons: ["Not available in US/UK", "No fiat options", "Bonus structure could be better"],
      featured: true,
      rank: 5,
      isActive: true,
    },
    {
      name: "Cloudbet",
      slug: "cloudbet",
      logo: "/logos/cloudbet.png",
      description: "Premium crypto sportsbook with the best odds and highest limits for serious bettors.",
      longDescription: "Cloudbet is the gold standard for serious crypto sports bettors. Established in 2013, they are one of the oldest and most trusted names in crypto gambling. Cloudbet is known for offering some of the best odds in the industry, the highest betting limits, and a premium user experience. Their platform also features a full casino suite and live dealer games. With a strong focus on security and fair play, Cloudbet has maintained an impeccable reputation over the years.",
      websiteUrl: "https://cloudbet.com",
      affiliateUrl: "https://cloudbet.com/?ref=betwithoutkyc",
      overallRating: 9.0,
      trustScore: 9.7,
      trustScoreLabel: "Excellent",
      oddsRating: 9.6,
      bonusRating: 8.5,
      uiRating: 9.2,
      supportRating: 9.0,
      payoutSpeed: "Under 10 minutes",
      minDeposit: "0.001 BTC",
      maxPayout: "$500,000",
      established: "2013",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "BCH", "USDT", "USDC", "DOGE", "LTC"],
      sportsCovered: ["Football", "Basketball", "Tennis", "Cricket", "Rugby", "Esports", "MMA", "Golf"],
      pros: ["Best odds available", "Highest betting limits", "Established since 2013", "Premium interface", "Strong reputation"],
      cons: ["Fewer cryptos than competitors", "Bonus requires wagering", "Higher minimum deposit"],
      featured: true,
      rank: 6,
      isActive: true,
    },
    {
      name: "Duelbits",
      slug: "duelbits",
      logo: "/logos/duelbits.png",
      description: "Fast-growing crypto casino and sportsbook with an esports focus and great promotions.",
      longDescription: "Duelbits has quickly risen through the ranks to become a favorite among younger crypto gambling enthusiasts. With a strong focus on esports betting and a sleek modern interface, Duelbits appeals to the gaming generation. Their platform offers competitive odds across major sports, a comprehensive casino section, and unique promotional events. The site supports multiple cryptocurrencies and offers fast withdrawals with minimal fees.",
      websiteUrl: "https://duelbits.com",
      affiliateUrl: "https://duelbits.com/?ref=betwithoutkyc",
      overallRating: 8.7,
      trustScore: 8.5,
      trustScoreLabel: "Very Good",
      oddsRating: 8.5,
      bonusRating: 9.0,
      uiRating: 9.3,
      supportRating: 8.2,
      payoutSpeed: "Under 30 minutes",
      minDeposit: "$1",
      maxPayout: "$500,000",
      established: "2020",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "LTC", "USDT", "SOL"],
      sportsCovered: ["Football", "Basketball", "Esports", "Tennis", "MMA"],
      pros: ["Great esports coverage", "Modern interface", "Good promotions", "Fast growing", "Creator partnerships"],
      cons: ["Relatively new platform", "Limited crypto options", "Support can be slow"],
      featured: true,
      rank: 7,
      isActive: true,
    },
    {
      name: "Rollbit",
      slug: "rollbit",
      logo: "/logos/rollbit.png",
      description: "Innovative crypto casino with NFT integration, trading features, and unique gambling experiences.",
      longDescription: "Rollbit stands out from the crowd with its innovative approach to crypto gambling. Beyond traditional casino games and sports betting, Rollbit offers NFT trading, crypto futures, and unique gamified experiences. Their platform features original games with provably fair algorithms, a comprehensive sportsbook, and a thriving marketplace for NFTs and collectibles. Rollbit's unique RLB token adds another layer of engagement for dedicated users.",
      websiteUrl: "https://rollbit.com",
      affiliateUrl: "https://rollbit.com/?ref=betwithoutkyc",
      overallRating: 8.4,
      trustScore: 7.8,
      trustScoreLabel: "Good",
      oddsRating: 8.0,
      bonusRating: 8.5,
      uiRating: 8.8,
      supportRating: 7.5,
      payoutSpeed: "Under 1 hour",
      minDeposit: "$0.10",
      maxPayout: "$1,000,000",
      established: "2020",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "SOL", "LTC", "USDT"],
      sportsCovered: ["Football", "Basketball", "Tennis", "Esports", "MMA"],
      pros: ["NFT integration", "Unique gaming features", "RLB token rewards", "Low minimum deposit", "Innovative platform"],
      cons: ["Can be complex for beginners", "Customer support needs improvement", "Newer platform"],
      featured: false,
      rank: 8,
      isActive: true,
    },
    {
      name: "Sportsbet.io",
      slug: "sportsbet-io",
      logo: "/logos/sportsbetio.png",
      description: "Leading crypto sportsbook with major sponsorships and a proven track record.",
      longDescription: "Sportsbet.io is part of the Yolo Group and has established itself as one of the most reputable crypto sportsbooks in the industry. With major sponsorships in football (including Premier League teams), Sportsbet.io brings legitimacy and trust to the crypto betting space. Their platform offers extensive sports coverage with competitive odds, live betting, and a smooth mobile experience. They also feature a casino section with popular slots and table games.",
      websiteUrl: "https://sportsbet.io",
      affiliateUrl: "https://sportsbet.io/?ref=betwithoutkyc",
      overallRating: 8.8,
      trustScore: 9.2,
      trustScoreLabel: "Excellent",
      oddsRating: 9.0,
      bonusRating: 8.0,
      uiRating: 8.8,
      supportRating: 8.5,
      payoutSpeed: "Under 15 minutes",
      minDeposit: "0.0001 BTC",
      maxPayout: "$500,000",
      established: "2016",
      license: "Curacao",
      cryptosAccepted: ["BTC", "ETH", "LTC", "USDT", "TRX", "XRP"],
      sportsCovered: ["Football", "Basketball", "Tennis", "Cricket", "Baseball", "MMA", "Esports", "Rugby"],
      pros: ["Major sports sponsorships", "Proven track record", "Great sports coverage", "Live betting", "Mobile-friendly"],
      cons: ["Bonuses could be better", "Limited original games", "Fewer crypto options"],
      featured: true,
      rank: 9,
      isActive: true,
    },
    {
      name: "WildVegas",
      slug: "wildvegas",
      logo: "/logos/wildvegas.png",
      description: "Example of a low-trust bookmaker - delayed payouts and poor customer service reported.",
      longDescription: "WildVegas has received numerous complaints from users regarding delayed withdrawals and unresponsive customer support. While their platform offers a range of casino games, the persistent payout issues have severely damaged their reputation in the crypto gambling community. We include them in our database to warn users about potential risks. Multiple users have reported waiting weeks for payouts that should be instant with cryptocurrency.",
      websiteUrl: "https://wildvegas.com",
      affiliateUrl: "",
      overallRating: 3.2,
      trustScore: 1.5,
      trustScoreLabel: "Avoid",
      oddsRating: 5.0,
      bonusRating: 6.0,
      uiRating: 5.5,
      supportRating: 2.0,
      payoutSpeed: "2-4 weeks",
      minDeposit: "$25",
      maxPayout: "$10,000",
      established: "2019",
      license: "Unknown",
      cryptosAccepted: ["BTC"],
      sportsCovered: ["Limited"],
      pros: ["Large game selection"],
      cons: ["Extremely slow payouts", "Poor customer support", "Questionable license", "User complaints", "Low withdrawal limits"],
      featured: false,
      rank: 99,
      isActive: true,
    },
  ];

  for (const bm of bookmakerData) {
    await db.insert(bookmakers).values(bm);
  }

  const allBookmakers = await db.select().from(bookmakers);
  const mystakeId = allBookmakers.find(b => b.slug === "mystake")?.id;
  const playbetId = allBookmakers.find(b => b.slug === "playbet")?.id;
  const bcGameId = allBookmakers.find(b => b.slug === "bc-game")?.id;
  const velobetId = allBookmakers.find(b => b.slug === "velobet")?.id;
  const stakeId = allBookmakers.find(b => b.slug === "stake")?.id;
  const cloudbetId = allBookmakers.find(b => b.slug === "cloudbet")?.id;
  const duelbitsId = allBookmakers.find(b => b.slug === "duelbits")?.id;
  const sportsbetId = allBookmakers.find(b => b.slug === "sportsbet-io")?.id;

  const bonusData = [
    { bookmakerId: mystakeId!, title: "120% Sports Welcome Bonus", description: "Get 120% match on your first deposit up to $600 with just 10x wagering requirement", bonusCode: null, bonusType: "welcome", value: "120% up to $600", wagerRequirement: "10x", minDeposit: "$20", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: mystakeId!, title: "10% Monthly Crypto Cashback", description: "Receive 10% cashback on all crypto losses every month - automatically credited", bonusCode: null, bonusType: "cashback", value: "10% Monthly", wagerRequirement: "None", minDeposit: null, expiresAt: null, isActive: true },
    { bookmakerId: mystakeId!, title: "35% Sports Reload Bonus", description: "Weekly 35% reload bonus on sports deposits every week", bonusCode: null, bonusType: "reload", value: "35% Reload", wagerRequirement: "15x", minDeposit: "$20", expiresAt: null, isActive: true },
    { bookmakerId: playbetId!, title: "200% Welcome Bonus", description: "Massive 200% match bonus up to 1,000 USDT plus 200 free spins on your first deposit", bonusCode: null, bonusType: "welcome", value: "200% up to 1,000 USDT", wagerRequirement: "30x", minDeposit: "$20", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: playbetId!, title: "200 Free Spins", description: "Get 200 free spins on top-tier slots when you make your first deposit", bonusCode: null, bonusType: "freebet", value: "200 Free Spins", wagerRequirement: "25x", minDeposit: "$20", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: bcGameId!, title: "300% Welcome Package", description: "Massive 300% bonus spread across your first 4 deposits", bonusCode: "BC300", bonusType: "welcome", value: "300% up to $20,000", wagerRequirement: "35x", minDeposit: "$1", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: bcGameId!, title: "Daily Free Spin", description: "Spin the Lucky Wheel daily for free crypto prizes", bonusCode: null, bonusType: "freebet", value: "Free Daily Spin", wagerRequirement: "1x", minDeposit: null, expiresAt: null, isActive: true },
    { bookmakerId: velobetId!, title: "150% Sports Welcome Bonus", description: "Get 150% bonus up to $1,000 on your first sports deposit", bonusCode: "NEWBONUS", bonusType: "welcome", value: "150% up to $1,000", wagerRequirement: "15x", minDeposit: "$10", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: velobetId!, title: "10% Crypto Cashback", description: "Monthly 10% cashback on all crypto deposit losses with zero wagering requirements", bonusCode: null, bonusType: "cashback", value: "10% Monthly Cashback", wagerRequirement: "None", minDeposit: null, expiresAt: null, isActive: true },
    { bookmakerId: velobetId!, title: "160% Crypto Casino Bonus", description: "Exclusive 160% bonus up to $1,000 for crypto deposits on casino games", bonusCode: null, bonusType: "welcome", value: "160% up to $1,000", wagerRequirement: "35x", minDeposit: "$10", expiresAt: "2026-12-31", isActive: true },
    { bookmakerId: stakeId!, title: "200% First Deposit Bonus", description: "Get a 200% match on your first crypto deposit up to $1,000", bonusCode: "CRYPTOBET200", bonusType: "welcome", value: "200% up to $1,000", wagerRequirement: "40x", minDeposit: "$10", expiresAt: "2026-06-30", isActive: true },
    { bookmakerId: stakeId!, title: "Weekly Reload Bonus", description: "10% reload bonus every Monday on your deposit", bonusCode: "RELOAD10", bonusType: "reload", value: "10% Weekly", wagerRequirement: "20x", minDeposit: "$20", expiresAt: null, isActive: true },
    { bookmakerId: cloudbetId!, title: "100% Welcome Bonus", description: "Double your first deposit with our 100% crypto match bonus", bonusCode: "CLOUD100", bonusType: "welcome", value: "100% up to 5 BTC", wagerRequirement: "25x", minDeposit: "0.001 BTC", expiresAt: "2026-06-30", isActive: true },
    { bookmakerId: duelbitsId!, title: "Instant Cashback", description: "Get instant cashback on all your bets - no wagering required", bonusCode: "DUELCASH", bonusType: "cashback", value: "Up to 15% Cashback", wagerRequirement: "None", minDeposit: "$5", expiresAt: null, isActive: true },
    { bookmakerId: sportsbetId!, title: "Multi Combo Boost", description: "Get up to 100% extra on your combo/parlay bets", bonusCode: null, bonusType: "odds_boost", value: "Up to 100% Boost", wagerRequirement: "None", minDeposit: null, expiresAt: null, isActive: true },
  ];

  for (const bonus of bonusData) {
    await db.insert(bonuses).values(bonus);
  }

  const blogData = [
    {
      title: "Top 5 Crypto Sportsbooks for 2026",
      slug: "top-5-crypto-sportsbooks-2026",
      excerpt: "Our expert team ranks the best cryptocurrency sportsbooks for secure betting with instant payouts and the best odds.",
      content: `<h2>The Best Crypto Sportsbooks of 2026</h2><p>The world of crypto sports betting continues to evolve rapidly. In 2026, several platforms stand out from the crowd with exceptional offerings for cryptocurrency bettors.</p><h3>1. MyStake - The Overall King</h3><p>MyStake takes the top spot with their incredible 120% welcome bonus with just 10x wagering, support for 50+ cryptocurrencies, and instant payouts. Their VIP program with up to 20% weekly cashback is unmatched.</p><h3>2. Playbet - Best Welcome Bonus</h3><p>Playbet offers the most generous welcome package with 200% up to 1,000 USDT plus 200 free spins. Their 4,500+ game library and fast crypto withdrawals make them a top choice.</p><h3>3. BC.Game - Best Crypto Variety</h3><p>With support for over 90 cryptocurrencies and one of the most generous bonus structures in the industry, BC.Game is perfect for those looking to maximize their betting value.</p><h3>4. Velobet - Best Cashback</h3><p>Velobet stands out with their 10% monthly crypto cashback with zero wagering requirements. Their 150% sports welcome bonus and multi-language support make them a global favorite.</p><h3>5. Stake - Most Trusted</h3><p>Established in 2017, Stake remains one of the most trusted names in crypto betting with instant payouts, excellent odds, and a legendary VIP program.</p>`,
      category: "guide",
      tags: ["sportsbooks", "rankings", "2026", "crypto betting"],
      publishedAt: "2026-01-15",
      isPublished: true,
    },
    {
      title: "How to Spot Crypto Betting Scams",
      slug: "how-to-spot-crypto-betting-scams",
      excerpt: "Learn how to identify fraudulent crypto betting sites and protect your funds with our comprehensive scam detection guide.",
      content: `<h2>Protecting Yourself from Crypto Betting Scams</h2><p>As the crypto betting industry grows, so do the number of scams. Here's how to protect yourself.</p><h3>Red Flags to Watch For</h3><ul><li><strong>No License:</strong> Legitimate platforms display their gambling license clearly.</li><li><strong>Delayed Payouts:</strong> If a site consistently takes weeks to process withdrawals, avoid it.</li><li><strong>Poor Reviews:</strong> Check our Trust Score ratings - any bookmaker below 5.0 should be approached with extreme caution.</li><li><strong>Unrealistic Bonuses:</strong> If a bonus seems too good to be true, it probably is.</li></ul><h3>How Our Trust Score Works</h3><p>We rate every bookmaker on a scale of 0-10 based on payout reliability, user complaints, licensing, and our own testing. A score of 0 means the platform has been confirmed as fraudulent, while 10 represents a perfectly trustworthy operation.</p>`,
      category: "safety",
      tags: ["scams", "safety", "trust score", "guide"],
      publishedAt: "2026-01-20",
      isPublished: true,
    },
    {
      title: "Understanding Crypto Betting Bonuses",
      slug: "understanding-crypto-betting-bonuses",
      excerpt: "A complete breakdown of deposit bonuses, free bets, cashback offers, and wagering requirements in crypto betting.",
      content: `<h2>The Complete Guide to Crypto Betting Bonuses</h2><p>Crypto betting platforms offer various types of bonuses to attract and retain players. Understanding how these work can significantly boost your betting bankroll.</p><h3>Types of Bonuses</h3><h4>Welcome Bonuses</h4><p>These are the most generous offers, typically matching your first deposit by 100-300%. Always check the wagering requirements before claiming.</p><h4>Reload Bonuses</h4><p>Regular bonuses offered to existing players, usually smaller percentages (10-50%) but with lower wagering requirements.</p><h4>Cashback Offers</h4><p>Some platforms return a percentage of your losses as cashback, often with no wagering requirements attached.</p><h4>Free Bets / Free Spins</h4><p>Risk-free betting opportunities that let you place wagers without using your own funds.</p><h3>Wagering Requirements Explained</h3><p>A 40x wagering requirement on a $100 bonus means you need to bet $4,000 before you can withdraw the bonus funds. Lower is always better.</p>`,
      category: "guide",
      tags: ["bonuses", "guide", "wagering", "promotions"],
      publishedAt: "2026-02-01",
      isPublished: true,
    },
  ];

  for (const post of blogData) {
    await db.insert(blogPosts).values(post);
  }

  console.log("Database seeded successfully!");
}
